### ISSUE TITLE
Intructions for compiling on Linux?

### ISSUE THREAD

**Issue by malamoo** [SasLuca/glfw-single-header#2]
Hey I was wondering if compilation works on Linux at the moment? The README only mentions Windows and Mac OSX.

**Comment by r-lyeh** [comment]
It works. Try `cc source.c -ldl -lm -lpthread`

**Comment by malamoo** [comment]
I tried but I get some errors when running `$ cc -I example/ example/*.c -ldl -lm -lpthread`:

/usr/bin/ld: /tmp/ccMqR1SJ.o: in function `_glfwRefreshContextAttribs':
test.c:(.text+0x823): undefined reference to `_glfwPlatformGetTls'
/usr/bin/ld: /tmp/ccMqR1SJ.o: in function `glfwMakeContextCurrent':
test.c:(.text+0xefb): undefined reference to `_glfwPlatformGetTls'
/usr/bin/ld: /tmp/ccMqR1SJ.o: in function `glfwGetCurrentContext':
test.c:(.text+0xfd9): undefined reference to `_glfwPlatformGetTls'
/usr/bin/ld: /tmp/ccMqR1SJ.o: in function `glfwSwapInterval':
test.c:(.text+0x10a8): undefined reference to `_glfwPlatformGetTls'
/usr/bin/ld: /tmp/ccMqR1SJ.o: in function `glfwExtensionSupported':
test.c:(.text+0x1154): undefined reference to `_glfwPlatformGetTls'
/usr/bin/ld: /tmp/ccMqR1SJ.o:test.c:(.text+0x1332): more undefined references to `_glfwPlatformGetTls' follow

**Comment by r-lyeh** [comment]
Good catch. The example.c file is missing a `#define LSH_GLFW_X11` in line 53
Try `cc *.c -I. -DLSH_GLFW_X11 -w -lm -lpthread -ldl` instead

**Comment by malamoo** [comment]
Sweet it's finally working :grin: thank you! I don't understand what these `LSH_*` macros are used for but I'm expecting the README will include some more documentation as time goes on. Then again I'm new to building C programs and OpenGL so that's a factor too.
